In [33]:
import numpy as np
import pandas as pd

In [34]:
dataset=pd.read_csv("communal.csv")

In [35]:
dataset.shape

(14, 2)

In [36]:
dataset

Title  Category
0   I'm able to do the work. I will accomplish wit...         1
1                      Ambition can help you to grow.         1
2   I am grateful enough to him for helping me. Hi...         2
3   My intelligence ang leadership ability will be...         1
4   Our manager is really organized and powerful. ...         1
5   This boy has a logical skill to solve any comp...         1
6   Their decision can bring justice, They have a ...         2
7   She is a powerful and independent girl. She ha...         1
8   Our neighbor is very gentle and polite. They g...         2
9   I'm really close to her. I love her polite and...         2
10  She is learning how to teach. She is a good te...         2
11  We are discussing about the welfare of out tea...         2
12  Her roommate is very loveable and open minded....         2
13  She is establishing herself with a lot of effo...         1

# Data cleaning

In [37]:
import re 
import nltk

nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

ps=PorterStemmer()
all_stopword= stopwords.words('english')
all_stopword.remove('not')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [38]:
corpus=[]

for i in range(0, 14):
    
    review = re.sub('[^a-zA-Z]', ' ', dataset['Title'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in set(all_stopword)]
    review = ' '.join(review)
    corpus.append(review)

In [39]:
corpus

['abl work accomplish without help confid',
 'ambit help grow',
 'grate enough help kind make loveabl way share belong realli warm',
 'intellig ang leadership abil abl overcom problem expert field outstand perform confid face oustand result',
 'manag realli organ power profession behavior make us proud',
 'boy logic skill solv complex problem outstand perform sucessful soon',
 'decis bring justic merci love attitud toward sens humor praiseworthi',
 'power independ girl discov lot thing excel manag leadership',
 'neighbor gentl polit genuin help other love behavior keep everyon unit',
 'realli close love polit help behavior discuss famili friend hospit natur',
 'learn teach good team player team work togeth trust',
 'discuss welfar team teach peopl talk sympathi squad share mutual resepect ritual',
 'roommat loveabl open mind offer tea yesterday care other roomat lot lover behavior',
 'establish lot effort power women deep insight goal orient mental allow overcom barrier']

# Transforming data

In [40]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()

In [41]:
x=vectorizer.fit_transform(corpus).toarray()
y=dataset.iloc[:,-1].values

In [42]:
x

array([[0, 1, 1, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [43]:
y

array([1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 1], dtype=int64)

In [14]:
#saving bow into pickle file
import pickle
path="D:\\DATA SCIENCE PROJECTS\\Agentic vs communal\\bow_train.pkl"
pickle.dump(vectorizer,open(path,"wb"))

# spliting data

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 0)

In [45]:
x.shape

(14, 109)

In [46]:
y.shape

(14,)

# Training model

In [47]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [48]:
predictions=classifier.predict(X_test)
print(predictions)

[2 2 2 2 2]


In [49]:


from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, predictions)
print(cm)

accuracy_score(y_test, predictions)

[[0 1]
 [0 4]]


0.8

In [52]:
#saving the model

In [54]:
import pickle
path="D:\\DATA SCIENCE PROJECTS\\Agentic vs communal\\model.pkl"
pickle.dump(classifier,open(path,"wb"))

In [22]:
from sklearn.svm import SVC

In [23]:
model2= SVC(probability=True)
model2.fit(X_train, y_train)

SVC(probability=True)

In [24]:
predictions2=model2.predict(X_test)
print(predictions2)

[1 1 1 1 1]


In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, predictions2)
print(cm)

accuracy_score(y_test, predictions2)

[[1 0]
 [4 0]]


0.2

In [26]:
from sklearn.neighbors import KNeighborsClassifier

In [27]:
KN = KNeighborsClassifier(n_neighbors=3)

In [29]:
KNN = KN.fit(X_train, y_train)

In [31]:
y_pred = KNN.predict(X_test)

In [32]:
y_pred

array([1, 1, 1, 1, 1], dtype=int64)

In [62]:
#tokenizing the words

In [67]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
joint_words = ' '.join(corpus)
print(joint_words)

separated_words = word_tokenize(joint_words)

print(separated_words)

abl work accomplish without help confid ambit help grow grate enough help kind make loveabl way share belong realli warm intellig ang leadership abil abl overcom problem expert field outstand perform confid face oustand result manag realli organ power profession behavior make us proud boy logic skill solv complex problem outstand perform sucessful soon decis bring justic merci love attitud toward sens humor praiseworthi power independ girl discov lot thing excel manag leadership neighbor gentl polit genuin help other love behavior keep everyon unit realli close love polit help behavior discuss famili friend hospit natur learn teach good team player team work togeth trust discuss welfar team teach peopl talk sympathi squad share mutual resepect ritual roommat loveabl open mind offer tea yesterday care other roomat lot lover behavior establish lot effort power women deep insight goal orient mental allow overcom barrier
['abl', 'work', 'accomplish', 'without', 'help', 'confid', 'ambit', '

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [61]:
with open('dictionary.txt', 'wb') as file:
    pickle.dump(separated_words, file)

In [62]:
with open ('dictionary.txt', 'rb') as file:
    Outlist = pickle.load(file)

In [64]:
Outlist

['abl',
 'work',
 'accomplish',
 'without',
 'help',
 'confid',
 'ambit',
 'help',
 'grow',
 'grate',
 'enough',
 'help',
 'kind',
 'make',
 'loveabl',
 'way',
 'share',
 'belong',
 'realli',
 'warm',
 'intellig',
 'ang',
 'leadership',
 'abil',
 'abl',
 'overcom',
 'problem',
 'expert',
 'field',
 'outstand',
 'perform',
 'confid',
 'face',
 'oustand',
 'result',
 'manag',
 'realli',
 'organ',
 'power',
 'profession',
 'behavior',
 'make',
 'us',
 'proud',
 'boy',
 'logic',
 'skill',
 'solv',
 'complex',
 'problem',
 'outstand',
 'perform',
 'sucessful',
 'soon',
 'decis',
 'bring',
 'justic',
 'merci',
 'love',
 'attitud',
 'toward',
 'sens',
 'humor',
 'praiseworthi',
 'power',
 'independ',
 'girl',
 'discov',
 'lot',
 'thing',
 'excel',
 'manag',
 'leadership',
 'neighbor',
 'gentl',
 'polit',
 'genuin',
 'help',
 'other',
 'love',
 'behavior',
 'keep',
 'everyon',
 'unit',
 'realli',
 'close',
 'love',
 'polit',
 'help',
 'behavior',
 'discuss',
 'famili',
 'friend',
 'hospit',
 '